"""Compare Buckler `_next/data` requests inside a HAR (native UI request vs companion request).

    python3 scripts/research/compare_buckler_har.py "/mnt/c/Users/<you>/Downloads/buckler.har"

Prints ONLY sanitized facts. Never prints cookies, Authorization/Set-Cookie values, bodies, or
user names. Headers are grouped as:
  browser   — generated by Chrome itself (UA, sec-*, accept-encoding/language, referer, …)
  next      — generated by Buckler's Next.js router (x-nextjs-data, x-middleware-*, purpose)
  app       — anything else (application-specific)
For each response: status, size, x-nextjs-* headers, and from pageProps only:
  common.statusCode, common.isError, common.loginUser.flg (booleans/numbers), size of `play` /
  `replay_list`, and the KEY NAMES of `common`.
"""

from __future__ import annotations

import base64
import json
import sys
from urllib.parse import parse_qsl, urlsplit

BROWSER = {
    "accept",
    "accept-encoding",
    "accept-language",
    "user-agent",
    "referer",
    "origin",
    "priority",
    "sec-gpc",
    "dnt",
    "connection",
    "host",
    "cache-control",
    "pragma",
}
SECRET = {"cookie", "authorization", "set-cookie", "proxy-authorization"}


def header_group(name: str) -> str:
    n = name.lower()
    if n in SECRET:
        return "secret"
    if n in BROWSER or n.startswith("sec-ch-") or n.startswith("sec-fetch-"):
        return "browser"
    if n.startswith("x-nextjs") or n.startswith("x-middleware") or n in {"purpose", "next-router-prefetch", "rsc", "next-url", "next-router-state-tree", "next-action"}:
        return "next"
    return "app"


def body_text(entry: dict) -> str | None:
    c = entry["response"].get("content", {})
    t = c.get("text")
    if t is None:
        return None
    if c.get("encoding") == "base64":
        try:
            return base64.b64decode(t).decode("utf-8", "replace")
        except Exception:  # noqa: BLE001
            return None
    return t


def summarize(entry: dict) -> dict:
    req, res = entry["request"], entry["response"]
    url = urlsplit(req["url"])
    headers = {"browser": {}, "next": {}, "app": {}, "secret": []}
    for h in req.get("headers", []):
        n = h["name"].lower()
        if n.startswith(":"):
            continue
        g = header_group(n)
        if g == "secret":
            headers["secret"].append(n)  # name only — proves presence, never the value
        elif n == "referer":
            headers[g][n] = urlsplit(h["value"]).path  # path only
        elif n == "user-agent":
            headers[g][n] = h["value"][:40] + "…"
        else:
            headers[g][n] = h["value"][:80]
    out = {
        "time": entry.get("startedDateTime"),
        "method": req["method"],
        "path": url.path,
        "query": dict(parse_qsl(url.query)),
        "headers": headers,
        "initiator": (entry.get("_initiator") or {}).get("type"),
        "status": res["status"],
        "redirectURL": urlsplit(res.get("redirectURL") or "").path or None,
        "bytes": (res.get("content") or {}).get("size"),
        "resp_headers": {
            h["name"].lower(): h["value"][:80]
            for h in res.get("headers", [])
            if h["name"].lower().startswith(("x-nextjs", "x-middleware", "x-cache", "content-type", "location"))
        },
    }
    text = body_text(entry)
    if text:
        out["bytes"] = len(text)
        try:
            pp = json.loads(text).get("pageProps", {})
            common = pp.get("common") or {}
            login = common.get("loginUser") or {}
            out["common"] = {
                "keys": sorted(common.keys()),
                "statusCode": common.get("statusCode"),
                "isError": common.get("isError"),
                "loginUser.flg": login.get("flg") if isinstance(login, dict) else None,
            }
            for k in ("play", "replay_list", "__N_REDIRECT"):
                if k in pp:
                    out[f"size.{k}"] = len(json.dumps(pp[k]))
        except (ValueError, AttributeError):
            out["json"] = False
    return out


def main() -> int:
    har = json.load(open(sys.argv[1], encoding="utf-8"))
    rows = [
        summarize(e)
        for e in har["log"]["entries"]
        if "/6/buckler/" in e["request"]["url"]
        and any(k in e["request"]["url"] for k in ("/_next/data/", "/api/", "play", "battlelog"))
        and not e["request"]["url"].endswith((".js", ".css", ".png", ".webp", ".svg", ".woff2"))
    ]
    for i, r in enumerate(rows):
        print(f"\n#{i}  {r['time']}  {r['method']} {r['path']}")
        print(json.dumps({k: v for k, v in r.items() if k not in ("time", "method", "path")}, indent=1, ensure_ascii=False))

    plays = [r for r in rows if r["path"].endswith("/play.json")]
    if len(plays) >= 2:
        a, b = plays[0], plays[-1]
        print("\n=== DIFF first vs last play.json (fields that differ) ===")
        for key in ("path", "query", "status", "bytes", "redirectURL", "initiator", "common", "size.play", "resp_headers"):
            if a.get(key) != b.get(key):
                print(f"{key}:\n  first: {a.get(key)}\n  last:  {b.get(key)}")
        for group in ("browser", "next", "app"):
            ha, hb = a["headers"][group], b["headers"][group]
            for name in sorted(set(ha) | set(hb)):
                if ha.get(name) != hb.get(name):
                    print(f"header[{group}] {name}:\n  first: {ha.get(name)}\n  last:  {hb.get(name)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
